spring:
  profiles:
    active: localdev
  application:
    name: student-management-system

server:
  port: 8080

company: DiyoTech
domain: IT

logging:
  file:
    name: myapp.log
  level:
    root: info
