spring:
  application:
    name: student-management-system
  datasource:
    url: jdbc:mysql://fb-dev:3306/nov24
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

company: DiyoTechDev
domain: IT
